description: "The Open Observatory of Network Interference (OONI) is a global community measuring internet censorship around the world. Run OONI Probe to detect internet censorship. Use OONI Explorer to track internet censorship worldwide in near real-time."

headless_cms:
  engine: "sveltia"
  site_url: "https://ooni.org"
  backend:
  name: "github"
  repo: "ooni/ooni.org"
